### ISSUE TITLE
When netflix plugin passes to chrome, chrome doesn't get login token

### ISSUE THREAD

**Issue by mdmallardi** [logi85/plugin.video.netflix#1]
I see in the original netflixbmc code there being a lot of steps to inject cookies in.  Please let me know what further information you need to help diagnose this.

OS:
Kodibuntu upgraded to a lubuntu 14.04.3 base
steps to reproduce:
use netflix plugin to navigate to a selected TV series episode.  Select to play
expected action:
Stream begins playing in Chrome in kiosk mode
action that happens:
Selected episode comes up in chrome, but netflix not logged in.

**Comment by logi85** [comment]
hey, should now work with chrome under linux and windows.

**Comment by mdmallardi** [comment]
This indeed does work now!  Thank you!
