### ISSUE TITLE
Chromium launcher (OpenELEC support)

### ISSUE THREAD

**Issue by talondnb** [logi85/plugin.video.netflix#4]
I used the following code for launchBrowser.sh in OpenELEC 6.0:

#!/bin/bash
for i in $@; do :; done
x="$i --kiosk"
/usr/bin/kodi-send -a "RunAddon(browser.chromium, $x)" &
exit 0

This was taken from from a Chromium remote control script designed to be used in OE with Netflix or Amazon Prime: https://www.dropbox.com/s/e80k4qrn6jr58rd/script.chromium_remotecontrol.1.2.zip?dl=0

This guide was followed, changing the Netflix installation part to install this plugin instead.

http://openelec.tv/forum/128-addons/77591-chromium-html5-guide-for-netflix-amazon-prime

**Comment by logi85** [comment]
Hi,

just added a setting "use chrome launcher". If enabled, it uses launchChromeLauncher(.cmd/.sh)
please give it a try.

**Comment by talondnb** [comment]
Just tested and works great, thanks logi85!
