### ISSUE TITLE
launchBrowser.cmd does not launch browser if path has a <space> in it.

### ISSUE THREAD

**Issue by markmoroni** [logi85/plugin.video.netflix#5]
In order to properly launch the launchBrowser.cmd file from play.py, you need to encapsulate the path in double quotes.

Line 155 of play.py should be changed from:
os.system(addon_path+'/resources/launchBrowser.cmd ' + url)

to:
os.system('"'+addon_path+'/resources/launchBrowser.cmd" ' + url)

**Comment by logi85** [comment]
Hi please try the newest version.
Should now work.
If it works, please close this issue.
Greetings
logi85

**Comment by markmoroni** [comment]
Verified!  Thanks!
